# .github/workflows/engine-cicd.yml
name: Deploy Calculation Engine to Azure

on:
  push:
    branches:
      - main  # This pipeline runs when code is pushed to the 'main' branch
    paths:
      - 'src/engine/**' # Only runs if files inside the engine folder change

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/engine'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Set up Python version'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: 'Install dependencies'
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt
        
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: 'func-vm22-tracer-engine' # <<< MAKE SURE THIS NAME IS CORRECT
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}