# FINAL, WORKING PIPELINE for the Calculation Engine
name: Deploy Calculation Engine to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'src/engine/**'

env:
  # This now points to the PARENT directory of our function.
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/engine' 
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Set up Python version'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: 'Install dependencies'
      run: pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt
        
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: 'func-vm22-tracer-engine'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}