# FINAL, SIMPLIFIED PIPELINE - Enables Remote Build
name: Build and Deploy Calculation Engine

on:
  push:
    branches:
      - main
    paths:
      - 'src/engine/**'
      - '.github/workflows/engine-cicd.yml'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/engine'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository code'
      uses: actions/checkout@v3

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: 'func-vm22-tracer-engine'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}