name: Deploy Web App to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'src/webapp/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-vm22-tracer-ui' # <<< MAKE SURE THIS NAME IS CORRECT
        package: 'src/webapp' 