name: Deploy Web App to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'src/webapp/**'
      - '.github/workflows/webapp-cicd.yml'
env:
  AZURE_WEBAPP_NAME: 'app-vm22-tracer-ui'    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './src/webapp'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '22.x' 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          npm install 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .